name: Frontend (React.js) workflow - Build and deploy app to S3 bucket

on: 
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "main"  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [18.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: Build install node modules and build project
        run: npm install
        run: npm run build
        working-directory: frontend


