name: Frontend (React.js) workflow - Build and deploy app to S3 bucket

on: 
  push:
    branches:
      - "main"
    paths:
      - "frontend/**"
  pull_request:
    branches: 
      - "main"  
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [18.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: Install node modules
        run: npm install
        working-directory: frontend
      - name: Build project
        run: npm run build
        working-directory: frontend


